version: "3.8"
services:
  backend:
    container_name: tiflo_backend
#    depends_on:
#      postgres:
#        condition: service_started
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./configs/config.yml:/configs/config.yml
    restart: always

#  postgres:
#    env_file:
#      - .env
#    image: postgres:15
#    container_name: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: ${DB_NAME}
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - ./db/init.sql:/docker-entrypoint-initdb.d/initdb.sql
#    restart: always