version: "3.8"
services:
  backend:
    container_name: tiflo_backend
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${CONFIG}:/configs
      - ${MEDIA}:/media/
    restart: always

  postgres:
    env_file:
      - .env
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      -  ${PG_DATA}:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/initdb.sql
    restart: always

  redis:
    env_file:
      - .env
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    environment:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        REDIS_DATABASES: 16
    volumes:
      - ${REDIS_DATA}:/data