db:
  connection_string: "host=postgres port=5432 user= dbname= options='-c search_path=public' password= sslmode=disable"

python:
  voice2text:
    address: ""
  image2text:
    address: ""

redis:
  host: ""
  port: ""
  user: ""
  password: ""
  dialTimeout: "10s"
  readTimeout: "10s"

auth:
  secret: ""
  salt: ""
